services:
  web:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    networks:
      - my_network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ./data/mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - my_network

networks:
  my_network:
    name: my_network
    driver: bridge